name: flutterapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
    path: ../../flutter_map
  sqflite:
  path:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  assets:
  - assets/berlin.mbtiles
  - assets/h1m.mbtiles
  - assets/h1m2.mbtiles
  - assets/hosmturkey1.mbtiles
  - assets/map/anholt_osmbright/12/2177/
  - assets/map/anholt_osmbright/12/2178/
  - assets/map/anholt_osmbright/12/2179/
  - assets/map/anholt_osmbright/12/2180/
  - assets/map/anholt_osmbright/12/2181/
  - assets/map/anholt_osmbright/13/4354/
  - assets/map/anholt_osmbright/13/4355/
  - assets/map/anholt_osmbright/13/4356/
  - assets/map/anholt_osmbright/13/4357/
  - assets/map/anholt_osmbright/13/4358/
  - assets/map/anholt_osmbright/13/4359/
  - assets/map/anholt_osmbright/13/4360/
  - assets/map/anholt_osmbright/13/4361/
  - assets/map/anholt_osmbright/13/4362/
  - assets/map/anholt_osmbright/13/4363/
  - assets/map/anholt_osmbright/14/8709/
  - assets/map/anholt_osmbright/14/8710/
  - assets/map/anholt_osmbright/14/8711/
  - assets/map/anholt_osmbright/14/8712/
  - assets/map/anholt_osmbright/14/8713/
  - assets/map/anholt_osmbright/14/8714/
  - assets/map/anholt_osmbright/14/8715/
  - assets/map/anholt_osmbright/14/8716/
  - assets/map/anholt_osmbright/14/8717/
  - assets/map/anholt_osmbright/14/8718/
  - assets/map/anholt_osmbright/14/8719/
  - assets/map/anholt_osmbright/14/8720/
  - assets/map/anholt_osmbright/14/8721/
  - assets/map/anholt_osmbright/14/8722/
  - assets/map/anholt_osmbright/14/8723/
  - assets/map/anholt_osmbright/14/8724/
  - assets/map/anholt_osmbright/14/8725/
  - assets/map/anholt_osmbright/14/8726/
  - assets/map/anholt_osmbright/14/8727/
  - assets/map/LeafletLocalMaps01_37b052/0/0/
  - assets/map/LeafletLocalMaps01_37b052/1/1/
  - assets/map/LeafletLocalMaps01_37b052/2/2/
  - assets/map/LeafletLocalMaps01_37b052/3/4/
  - assets/map/LeafletLocalMaps01_37b052/4/9/
  - assets/map/LeafletLocalMaps01_37b052/5/18/
  - assets/map/LeafletLocalMaps01_37b052/17/77490/
  - assets/map/LeafletLocalMaps01_37b052/17/77491/
  - assets/map/LeafletLocalMaps01_37b052/17/77492/
  - assets/map/LeafletLocalMaps01_37b052/17/77493/
  - assets/map/LeafletLocalMaps01_37b052/17/77494/
  - assets/map/LeafletLocalMaps01_37b052/17/77495/
  - assets/map/LeafletLocalMaps01_37b052/17/77496/
  - assets/map/LeafletLocalMaps01_37b052/17/77497/
  - assets/map/LeafletLocalMaps01_37b052/17/77498/
  - assets/map/LeafletLocalMaps01_37b052/17/77499/
  - assets/map/LeafletLocalMaps01_37b052/17/77500/
  - assets/map/LeafletLocalMaps01_37b052/17/77501/
  - assets/map/LeafletLocalMaps01_37b052/17/77502/
  - assets/map/LeafletLocalMaps01_37b052/17/77503/
  - assets/map/LeafletLocalMaps01_37b052/17/77504/
  - assets/map/LeafletLocalMaps01_37b052/17/77505/
  - assets/map/LeafletLocalMaps01_37b052/17/77506/
  - assets/map/LeafletLocalMaps01_37b052/17/77507/
  - assets/map/LeafletLocalMaps01_37b052/18/154981/
  - assets/map/LeafletLocalMaps01_37b052/18/154982/
  - assets/map/LeafletLocalMaps01_37b052/18/154983/
  - assets/map/LeafletLocalMaps01_37b052/18/154984/
  - assets/map/LeafletLocalMaps01_37b052/18/154985/
  - assets/map/LeafletLocalMaps01_37b052/18/154986/
  - assets/map/LeafletLocalMaps01_37b052/18/154987/
  - assets/map/LeafletLocalMaps01_37b052/18/154988/
  - assets/map/LeafletLocalMaps01_37b052/18/154989/
  - assets/map/LeafletLocalMaps01_37b052/18/154990/
  - assets/map/LeafletLocalMaps01_37b052/18/154991/
  - assets/map/LeafletLocalMaps01_37b052/18/154992/
  - assets/map/LeafletLocalMaps01_37b052/18/154993/
  - assets/map/LeafletLocalMaps01_37b052/18/154994/
  - assets/map/LeafletLocalMaps01_37b052/18/154995/
  - assets/map/LeafletLocalMaps01_37b052/18/154996/
  - assets/map/LeafletLocalMaps01_37b052/18/154997/
  - assets/map/LeafletLocalMaps01_37b052/18/154998/
  - assets/map/LeafletLocalMaps01_37b052/18/154999/
  - assets/map/LeafletLocalMaps01_37b052/18/155000/
  - assets/map/LeafletLocalMaps01_37b052/18/155001/
  - assets/map/LeafletLocalMaps01_37b052/18/155002/
  - assets/map/LeafletLocalMaps01_37b052/18/155003/
  - assets/map/LeafletLocalMaps01_37b052/18/155004/
  - assets/map/LeafletLocalMaps01_37b052/18/155005/
  - assets/map/LeafletLocalMaps01_37b052/18/155006/
  - assets/map/LeafletLocalMaps01_37b052/18/155007/
  - assets/map/LeafletLocalMaps01_37b052/18/155008/
  - assets/map/LeafletLocalMaps01_37b052/18/155009/
  - assets/map/LeafletLocalMaps01_37b052/18/155010/
  - assets/map/LeafletLocalMaps01_37b052/18/155011/
  - assets/map/LeafletLocalMaps01_37b052/18/155012/
  - assets/map/LeafletLocalMaps01_37b052/18/155013/
  - assets/map/LeafletLocalMaps01_37b052/18/155014/